# Generated by Django 4.2.2 on 2023-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
                ("url", models.URLField(blank=True)),
                ("github_repo", models.URLField(blank=True)),
                ("date", models.DateField()),
                ("tags", models.ManyToManyField(to="projects.category")),
            ],
        ),
    ]
