# Generated by Django 4.2.2 on 2023-06-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="resolution",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
