# Generated by Django 4.2.2 on 2023-06-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="images/profile"),
        ),
    ]
