# Generated by Django 4.2.2 on 2023-06-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profile"},
        ),
        migrations.AlterModelOptions(
            name="urls",
            options={"verbose_name_plural": "URLs"},
        ),
    ]
